backoffice/urls.py
from django.contrib import admin
from django.urls import path, include
from student import views
# django.contrib.auth 앱을 사용 => views.py 파일을 수정 할 필요는 없다.
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    
    path('student/',include('student.urls')),
    # student/detail
    # student/detail/create

]   

student/urls.py
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path('', views.student_list, name='list'),
    path('detail/<int:student_id>/', views.detail, name='detail'),
    path('modify/<int:student_id>/', views.modify, name='modify'),
    path('delete/<int:student_id>/', views.delete, name='delete'),
    path('create/', views.student_create, name='create'),
]

student/models.py
from django.db import models
# from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User


class Student(models.Model):
    GENDER_CHIOCES = (
        ('M','Male'),
        ('F','Female'),
    )
    MAINCHOICE=(
        ("Library","Library"),
        ("Voca","Voca"),
        ("NF","Library")
    )
    LIBRARYCHOICE = (
        ('R(1:20)','R(1:20)'),
        ('S(1:40)','S(1:40)'),
        ('I(2:00)','I(2:00)')
    )

    VOCALIBRARYCHOICE = (
        ('RV(1:40)','RV(1:40)'),
        ('SV(2:00)','SV(2:00)'),
        ('IV(2:20)','I(2:20)')
    )
    COUNTCHOICE = (
        ('12','12'),
        ('24','24'),
        ('36','36'),
        ('48','48')
    )
    
    # general information
    objects = models.Manager()
    name = models.CharField(max_length=5)
    gender = models.CharField(max_length=200, choices=GENDER_CHIOCES)
    birth = models.DateField()
    school = models.CharField(max_length=50)
    grade = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(6)])
    phone = models.CharField(max_length=20)
    level = models.PositiveIntegerField(null=True, blank=True)
    create_date = models.DateField()
    end_date = models.DateField()
    modify_date = models.DateField(null=True, blank=True)
    #  course 
    main = models.CharField(max_length=30, choices=MAINCHOICE, null=True, blank=True)
    library = models.CharField(max_length=30, choices=LIBRARYCHOICE,null=True, blank=True)
    voca_library = models.CharField(max_length=30, choices= VOCALIBRARYCHOICE,null=True, blank=True)
    count = models.CharField(max_length=30, choices= COUNTCHOICE,null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.name
        



        
# class Course(models.Model):
#     MAINCHOICE=(
#         ("Library","Library"),
#         ("Voca","Voca"),
#         ("NF","Library")
#     )
#     LIBRARYCHOICE = (
#         ('R(1:20)','R(1:20)'),
#         ('S(1:40)','S(1:40)'),
#         ('I(2:00)','I(2:00)')
#     )

#     VOCALIBRARYCHOICE = (
#         ('RV(1:40)','RV(1:40)'),
#         ('SV(2:00)','SV(2:00)'),
#         ('IV(2:20)','I(2:20)')
#     )
#     COUNTCHOICE = (
#         ('12','12'),
#         ('24','24'),
#         ('36','36'),
#         ('48','48')
#     )
#     objects = models.Manager()
#     student = models.ForeignKey(Student, on_delete=models.CASCADE)
#     main = models.CharField(max_length=30, choices=MAINCHOICE)
#     library = models.CharField(max_length=30, choices=LIBRARYCHOICE)
#     voca_library = models.CharField(max_length=30, choices= VOCALIBRARYCHOICE)
#     count = models.CharField(max_length=30, choices= COUNTCHOICE)
#     content = models.TextField()

#     def __str__(self):
#         return str(self.student)

student/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Student
# from student.models import Student

class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

# 장고 모델 폼은 내부 class meta 클래스를 반드시 가져와야 하며, meta 에는 모델 폼이 사용할 모델과
# 모델의 필드들을 적어야한다. 즉, model은 User 와 연결 되어 있고, 필드는 username과 email을 사용한다.
    
    class Meta:
        model = User
        fields = ('username', 'email')

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields =[
            'name',
            'gender',
            'birth',
            'school',
            'grade',
            'phone',
            'create_date',
            'end_date',
            'main',
            'library',
            'voca_library',
            'count',
            'content'
        ]

student/views.py
from .models import Student
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .forms import UserForm, StudentForm
from django.utils import timezone        
# from django.views.generic import ListView

# Create your views here
def index(request):
    return render(request, 'index.html')

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserForm()
    return render(request, 'signup.html', {'form':form})
            
@login_required
def student_list(request):
    
    page = request.GET.get('page', 1)
    student_list = Student.objects.order_by('-id')
    paginator = Paginator(student_list, 10)
    page_obj = paginator.get_page(page)
    context = {'student_list': page_obj}
    return render(request, 'student/student_list.html', context)


@login_required
def detail(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    context = {'student': student}  
    return render(request,'student/student_detail.html', context)

@login_required
def student_create(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            student = form.save(commit=False)
            user = request.user
            student.author = user
            student.save()
            return redirect ('/')
    else:
        form = StudentForm()
    
    context={'form':form}
    return render(request, 'student/student_form.html', context)


@login_required
def modify(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            student = form.save(commit=False)
            student.modify_date = timezone.now()  # 수정일시 저장
            student.author = request.user
            student.save()
            return redirect('student:detail', student_id = student.id)
    else:
        form = StudentForm(instance=student)
    context = {'form':form}
    return render(request, 'student/student_form.html',context)

@login_required
def delete(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    student.delete()
    return redirect('student:list')

student/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <title>backoffice</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- 리스트 : 부트스트랩은 모바일 우선이라 화면이 작으면 아래로 쌓아서 내려온다 -->
        <a class="navbar-brand" href="{% url 'index'%}">Home</a>
        {% if user.is_authenticated %}
        <ul class="navbar-nav navbar-dark">
            <li class="nav-item active"> <a class="nav-link" href="">직원관리</a> </li>
            <li class="nav-item active"> <a class="nav-link" href="{% url 'student:list'%}">학생관리</a> </li>
        </ul>
        {%else%}
        <ul class="navbar-nav navbar-dark">
            <li class="nav-item active"> <a class="nav-link" href="" id="open" onclick="javascript:btn()">직원관리</a></li>
            <li class="nav-item active"> <a class="nav-link" href="" id="open" onclick="javascript:btn()">학생관리</a> </li>
        </ul>
        <script>
            function btn() {
                alert('로그인 후 사용가능합니다.')
            }
        </script>
        {%endif%}
        {% if user.is_authenticated %}
        <ul class="navbar-nav  ml-auto ">
            <li class="nav-item active"> <a class="nav-link" href="{%url 'logout'%}">{{user.username}} (로그아웃)</a>
            <li class="nav-item active"> <a class="nav-link" href="{%url 'student:create'%}">학생등록</a>
            </li>
            <!-- <li class="nav-item active"> <a class="nav-link" >관리자: {{user.username}}</a> </li> -->
        </ul>
        {%else%}
        <ul class="navbar-nav  ml-auto ">
            <li class="nav-item active"> <a class="nav-link" href="{%url 'login'%}">로그인</a> </li>
            <li class="nav-item active"> <a class="nav-link" href="{%url 'signup'%}">회원가입</a> </li>
        </ul>
        {%endif%}
    </nav>
    {%block content%}
    {%endblock%}
    <footer class="text-center text-white fixed-bottom" style="background-color:#343a40;">
        <div class="footer-copyright text-center py-3">© 2021 Copyright: rockjeon
        </div>
    </footer>
    
    <script src="{% static 'jquery-3.6.0.min.js'%}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    {%block script%}
    {%endblock%}
</body>

</html>

student/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

student/templates/index.html
{%extends 'base.html'%}
{%block content%}
<span class="decoration-clone bg-gradient-to-b from-yellow-400 to-red-500 text-transparent ...">
    Hello<br>
    World
  </span>
{%endblock%}

student/templates/login.html
{%extends 'base.html'%}
{%block content%}
<div class="container">
<form method="POST" class="post-form" action="{%url 'login'%}">
    {% csrf_token %}
    {%include "form_errors.html"%}
    <div class="mb-3">
        <label for="username" class="form-label">사용자 ID</label>
        <input type="text" class="form-control col-md-4" id="username" name="username" value="{{form.username.value|default_if_none:''}}">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">비밀번호</label>
        <input type="password" class="form-control col-md-4" id="password" name="password" value="{{ form.password.value|default_if_none:'' }}" >
    </div>
    <!-- <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div> -->
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{%endblock%}

student/templates/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>회원가입</h4>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

student/templates/student/student_create.html
{%extends 'base.html'%}
{%block content%}
<style>
    select {
        width: 200px;
    }
</style>
<form action="{% url 'student:create' %}" method="POST" >
<div class="container">
    <h5 class="my-3 border-bottom pb-2">학생등록</h5>

    {% csrf_token %}
    {% include 'form_errors.html' %}
    
    <div class=" container my-3 row">
        <div class="name col-md-4"">
            <input type=" email" class="form-control" id="name" placeholder="이름" value="{{ form.name.value|default_if_none:'' }}">
        </div>
        <div class="school col-md-4">
            <input type="email" class="form-control" id="school" placeholder="학교" value="{{ form.school.value|default_if_none:'' }}">
        </div>
        <div class="phone col-md-4" style="justify-content: right;">
            <input type="email" class="form-control" id=phone" placeholder="번호" value="{{ form.school.phone|default_if_none:'' }}">
        </div>
    </div>
    <!-- --------------------------------------------------------------------------------------------------------- -->

    <div class=" container my-3 row">
        <div class="name col-md-4"">
        <label for="">등록날짜</label>
        <input type=" email" class="form-control" id="create_date" placeholder="이름">
        </div>
        <div class="school col-md-4">
            <label for="">마감날짜</label>
            <input type="email" class="form-control" id="end_date" placeholder="학교">
        </div>
        <div class="phone col-md-4" style="justify-content: right;">
            <label for="">생일</label>
            <input type="email" class="form-control" id="birth" placeholder="번호">
        </div>
    </div>
        <div class="row" style="justify-content: center;">
            <button type="button" class="btn btn-primary btn-lg" type="submit">등록하기</button>
        </div>
    </form>
</div>
{%endblock%}

student/templates/student/student_create_detail.html
{%extends 'base.html'%}
<!-- --------------------------------------------------------------------------------------------------------- -->
{%block content%}
<div class=" container my-3 row">
    <div class="name col-md-4"">
        <label for="">성별</label> :
        <select class=" form-select" aria-label="Default select example">
        <option selected>성별을 선택해주세요</option>
        <option value="M">남자</option>
        <option value="F">여자</option>
        </select>
    </div>
    <div class="school col-md-4">
        <label for="">학년</label> :
        <select class=" form-select" aria-label="Default select example">
            <option selected>학년을 선택해주세요
            <option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
        </select>
    </div>
    <div class="phone col-md-4" style="justify-content: right;">
        <label for="">레벨</label> :
        <select class=" form-select" aria-label="Default select example">
            <option selected>레벨을 선택해주세요</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
        </select>
    </div>
</div>
<div class="row" style="justify-content: center;">
    <button type="button" class="btn btn-primary btn-lg" type="submit">등록하기</button>
</div>
</form>
<h5 class="my-3 border-bottom pb-2">코스등록</h5>
<div class=" container my-3 row">
    <div class="name col-md-3"">
        <label for="">main(course)</label> 
        <select class=" form-select" aria-label="Default select example">
        <option selected>메인코스를 선택해주세요</option>
        <option value="1">Library</option>
        <option value="2">Voca</option>
        <option value="3">NF</option>
        </select>
    </div>
    <div class="school col-md-3">
        <label for="">Library</label> :
        <select class=" form-select" aria-label="Default select example">
            <option selected>시간을 선택해주세요</option>
            <option value="1">R(1:20</option>
            <option value="2">S(1:40)</option>
            <option value="3">I(2:00)</option>
        </select>
    </div>
    <div class="phone col-md-3" style="justify-content: right;">
        <label for="">Voca + Library</label> :
        <select class=" form-select" aria-label="Default select example">
            <option selected>시간을 선택해주세요</option>
            <option value="1">RV(1:40)</option>
            <option value="2">SV(2:00)</option>
            <option value="3">IV(2:20)</option>
        </select>
    </div>
    <div class="phone col-md-3" style="justify-content: right;">
        <label for="">Count</label>
        <select class=" form-select" aria-label="Default select example" id="count">
            <option selected>횟수를 선택해주세요.</option>
            <option value="1">12</option>
            <option value="2">24</option>
            <option value="3">36</option>
            <option value="3">48</option>
        </select>
    </div>
</div>
<div class="col-md-12 my-3">
    <label for="exampleFormControlTextarea1" class="form-label">특이사항</label>
    <textarea class="form-control" placeholder="특이사항을 입력하세요" style="height: 300px;"></textarea>
</div>
{%endblock%}

student/templates/student/student_detail.html
{%extends 'base.html' %}
{%block content%}
<style>
    textarea {
        height: 200px;
        
    }
    .container{
        border: 1px solid black;
        height: 712px;
    }
    .button{
        height: 40px;
    }
</style>
<div class="container my-3" id="box">
    <div class='row'>
        <div class="head col-md-12" style="justify-content: center;">
            <h1 style="text-align: center;">{{student.name}}</h1>
            <div>
                <p style="text-align: right;">등록자: {{student.author}}</p>
            </div>
        </div>
    </div>
    <div class=" button row" style="justify-content:flex-end;">
        <div class="modify">
            <a href="{% url 'student:modify' student.id %}" class="btn btn-secondary btn-sm" role="button">수정</a>
            <a href="#" class="delete btn btn-danger btn-sm" data-uri="{% url 'student:delete' student.id  %}">삭제</a>
        </div>
    </div>
<div class="row" style="justify-content: center;">
    <div class="card" style="width:30rem;">
        <div class="card-body">
            <h5 class="card-title" style="text-align: center;">General Information</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">학교: {{student.school}}</li>
            <li class="list-group-item">학년: {{student.grade}}학년</li>
            <li class="list-group-item">기간: {{student.create_date}}~{{student.end_date}}</li>
        </ul>
    </div>
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title" style="text-align: center;">Course Detail</h5>

        </div>
        <ul class="list-group list-group-flush">
            {%if student.main == None%}
                <li class="list-group-item">Course: 등록되지 않음</li>
            {%else %}
                <li class="list-group-item" >Course: {{student.main}}</li>
            {%endif%}
            
            {%if student.library == None%}
                <li class="list-group-item">Library: 등록되지 않음</li>
            {%else%}
                <li class="list-group-item">Library: {{student.library}}</li>
            {%endif%}
            {%if student.voca_library == None%}
                <li class="list-group-item">Voca+Library: 등록되지않음</li>
            {%else%}
                <li class="list-group-item">Voca+Library: {{student.voca_library}}</li>
            {%endif%}
            {%if student.count == None%}
                <li class="list-group-item">Count: 등록되지않음</li>
            {%else%}
                <li class="list-group-item">Count: {{student.count}}</li>
            {%endif%}
        </ul>
    </div>
</div>
<h1 style="text-align: center;">특이사항</h1>
<div class="row" style="justify-content: center;">
    {%if student.content == None%}
    <textarea {% if not user.is_authenticated %}disabled{% endif %} id="textarea" 
        style="width: 100%;" disabled></textarea>
    {%else%}
    <textarea {% if not user.is_authenticated %}disabled{% endif %} id="textarea" 
        style="width: 100%;" disabled>{{student.content}}</textarea>
    {%endif%}
    </div>
</div>
{%endblock%}
{%block script%}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

student/templates/student/student_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">학생등록하기*</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger " role="alert">
            <div class="row"><strong>* 학생등록사항은 모두 필수 항목입니다.(level 제외)</strong></div><br>
            <div class="alert-heading">
                {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {% endif %}
                {{ field.errors }}
                {% endfor %}
            </div>
        </div>
        {% endif%}
        <div class="general">
            <div class=" container my-3 row">
                <div class="name col-md-4"">
                    <label for="">이름</label>
            <input type=" text" class="form-control" id="name" placeholder="이름"
                    value="{{ form.name.value|default_if_none:'' }}" name="name">
                </div>
                <div class="school col-md-4">
                    <label for="">학교</label>
                    <input type="text" class="form-control" id="school" placeholder="학교"
                        value="{{ form.school.value|default_if_none:'' }}" name="school">
                </div>
                <div class="phone col-md-4" style="justify-content: right;">
                    <label for="">전화번호</label>
                    <input type="tel" class="form-control" id=phone" placeholder="010-0000-0000"
                        pattern="[0-9]{3}-[0-9]{4}-[0-9]{4}" required value="{{ form.phone.value|default_if_none:'' }}"
                        name="phone">
                    <small>Format: 010-0000-0000</small>
                </div>
            </div>
            <div class=" container my-3 row">
                <div class="name col-md-4"">
                <label for="">등록날짜</label>
                {%if form.create_date.value%}
                    <input type="text" class="form-control" id="create_date" placeholder="등록날짜"
                        value="{{ form.create_date.value|default_if_none:'' }}" name="create_date">
                {%else%}
                    <input type="date" class="form-control" id="create_date" placeholder="등록날짜"
                    value="{{ form.create_date.value|default_if_none:'' }}" name="create_date">
                {%endif%}
                </div>
                <div class="school col-md-4">
                    <label for="">마감날짜</label>
                    {%if form.end_date.value%}
                        <input type="text" class="form-control" id="end_date" placeholder="마감날짜"
                            value="{{ form.end_date.value|default_if_none:'' }}" name="end_date">
                    {%else%}
                        <input type="date" class="form-control" id="end_date" placeholder="마감날짜"
                            value="{{ form.end_date.value|default_if_none:'' }}" name="end_date">
                    {%endif%}
                    </div>
                <div class="phone col-md-4" style="justify-content: right;">
                    <label for="">생일</label>
                    {%if form.birth.value%}
                        <input type="text"class="form-control" id="birth" placeholder="생일"
                            value="{{ form.birth.value|default_if_none:'' }}" name="birth">
                    {%else%}
                        <input type="date" class="form-control" id="birth" placeholder="생일"
                            value="{{ form.birth.value|default_if_none:'' }}" name="birth">
                    {%endif%}
                </div>
            </div>
            <div class="container my-3 row">
                <div class="name col-md-4"">
                <label for="">성별</label>
                {%if form.gender.value == 'M'%}
                <input type="radio" id="gender" name="gender" value="M" checked>
                    <label for="M">Male</label>
                    <input type="radio" id="gender" name="gender" value="F">
                    <label for="F">Female</label>
                {%elif form.gender.value == "F" %}
                <input type="radio" id="gender" name="gender" value="M">
                    <label for="M">Male</label>
                <input type="radio" id="gender" name="gender" value="F" checked>
                    <label for="F">Female</label>
                {%else%}
                <input type="radio" id="gender" name="gender" value="M">
                <label for="M">Male</label>
                <input type="radio" id="gender" name="gender" value="F">
                <label for="F">Female</label>
                {%endif%}
                
                </div>
                <div class=" school col-md-4">
                    <label for="grade">학년</label> :
                    <select class=" form-select" aria-label="Default select example" name="grade">
                        <option selected>{{form.grade.value|default_if_none:''}}</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                    </select>

                </div>
                <div class="phone col-md-4" style="justify-content: right;">
                    <label for="level">레벨</label> :
                    <select class=" form-select" aria-label="Default select example" name="level">
                        <option selected>{{form.level.value|default_if_none:''}}</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </div>
            </div>
        </div>

        <h5 class="my-3 border-bottom pb-2">코스등록</h5>
        <div class=" container my-3 row">
            <div class="name col-md-3"">
                <label for="">main(course)</label><br> 
                <select class=" form-select" aria-label="Default select example" name="main">
                <option selected value="">{{form.main.value|default_if_none:''}}</option>
                <option value="Library">Library</option>
                <option value="Voca">Voca</option>
                <option value="NF">NF</option>
                </select>
            </div>
            <div class="school col-md-3">
                <label for="">Library</label><br>
                <select class=" form-select" aria-label="Default select example" name="library">
                    <option selected>{{form.library.value|default_if_none:''}} </option>
                    <option value="R(1:20)">R(1:20</option>
                    <option value="S(1:40)">S(1:40)</option>
                    <option value="I(2:00)">I(2:00)</option>
                </select>
            </div>
            <div class="phone col-md-3" style="justify-content: right;">
                <label for="">Voca + Library</label><br>
                <select class=" form-select" aria-label="Default select example" name="voca_library">
                    <option selected>{{form.voca_library.value|default_if_none:''}} </option>
                    <option value="RV(1:40)">RV(1:40)</option>
                    <option value="SV(2:00)">SV(2:00)</option>
                    <option value="IV(2:20)">IV(2:20)</option>
                </select>
            </div>
            <div class="phone col-md-3" style="justify-content: right;">
                <label for="">Count</label><br>
                <select class=" form-select" aria-label="Default select example" id="count" name="count">
                    <option selected>{{form.count.value|default_if_none:''}}</option>
                    <option value="12">12</option>
                    <option value="24">24</option>
                    <option value="36">36</option>
                    <option value="48">48</option>
                </select>
            </div>
        </div>
        <div class="col-md-12 my-3">
            <label for="content" class="form-label">특이사항</label>
            <textarea class="form-control" placeholder="특이사항을 입력하세요" name="content" id="content" >{{form.content.value|default_if_none:''}}</textarea>
        </div>
        <div class="row" style="justify-content: flex-end;">
            <button type="submit" class="btn btn-primary">등록</button>
        </div>

    </form>
</div>
{% endblock %}